### ISSUE TITLE
Add `templates` to `flake`

### ISSUE THREAD

**Issue by 9glenda** [hercules-ci/flake-modules-core#191]
Add the templates option to `flake` in order to be able to use `nix init -t`

**Comment by roberth** [comment]
Templates aren't built and don't involve a system string, so I think it should go in `flake` rather than `perSystem`.
It seems that if you want the template to be built rather than copied, that would require a new feature in nix itself.

[`nix init` docs](https://nixos.org/manual/nix/stable/command-ref/new-cli/nix3-flake-init.html#template-definitions)
